Added ability to specify verification rules in the root of reports config
Kotlin/kotlinx-kover pull request #430
Opened 2023-07-11 16:56 UTC by shanshin

Now it is not necessary to specify the same rules in different report variants, it is enough to specify them at the root, and they will be inherited in each variant, if they are not explicitly overridden.

2023-07-14 17:09 UTC, sandwwraith requested changes

2023-07-14 17:09 UTC, sandwwraith commented on kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/KoverReportExtension.kt
> +     * Specify common filters for all report variant, these filters will be inherited in HTML/XML/verification reports.
```suggestion
     * Specify common filters for all report variants, these filters will be inherited in HTML/XML/verification reports.
```

2023-07-14 17:36 UTC, shanshin commented on docs/gradle-plugin/configuring.md
> +    // verification rules for verification tasks in all variants
I don't think it's worth mentioning at this level, because in most cases users don't even need to know about `defaults { verify { rule { ...} } }`

2023-07-14 17:42 UTC, shanshin commented on kover-gradle-plugin/examples/jvm/defaults/build.gradle.kts
> +                    minValue = 2
This example is intended only to demonstrate all possible settings, it does not check any specific cases

2023-07-14 17:48 UTC, sandwwraith commented on docs/gradle-plugin/configuring.md
> +    // verification rules for verification tasks in all variants
But you have `defaults { verify { rule { ...} } }` literally below. In that case, either delete second one or add a note that `defaults { verify ` replaces just `verify {`

2023-07-17 16:31 UTC, sandwwraith approved these changes

2023-07-17 19:34 UTC, merged