Added ability to supplement coverage values from external binary reports
Kotlin/kotlinx-kover pull request #663
Opened 2024-08-02 11:07 UTC by shanshin

This will allow to build reports based on tests run on various machines.

Relates #585
Relates #645

2024-08-05 12:34 UTC, sandwwraith requested changes

2024-08-05 12:34 UTC, sandwwraith commented on kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/KoverReportsConfig.kt
> +    public val additionalBinaryReports: SetProperty<File>
Documentation is missing

2024-08-05 12:34 UTC, sandwwraith commented on kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/KoverReportsConfig.kt
> +    public val additionalBinaryReports: SetProperty<File>
It should probably also be somewhere in `.md` files?

2024-08-07 12:37 UTC, sandwwraith approved these changes

2024-08-07 12:54 UTC, shanshin commented on kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/KoverReportsConfig.kt
> +     * Coverage from specified classes will be use in corresponding Kover reports.
Yep

2024-08-07 12:54 UTC, merged